rpgdle/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash
from rpgdle.extensions import db
from rpgdle.models import User
import os

auth = Blueprint("auth", __name__)

@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method =="POST":
        name = request.form["name"]
        password = request.form["password"]
        user = User.query.filter_by(name=name).first()
        error_message = ""
        if not user or not check_password_hash(user.password, password):
            error_message = "Could not login. Check creds"
        if not error_message:
            login_user(user)
            return redirect(url_for("main.index"))
    return render_template("login.html")

@auth.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        name = request.form["name"]
        unhashed_password = request.form["password"]
        passphrase = request.form["passphrase"]
        check = os.environ.get("LOGIN_SECRET")
        check = check.split(",")
        print("CHECK:");
        print(check);
        #if passphrase in check (array)
        if passphrase in check:
        #if passphrase == check:
            user = User(name=name, unhashed_password=unhashed_password, groups=passphrase, admin=False)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("auth.login"))
        return render_template("register.html")

    return render_template("register.html")

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

rpgdle/routes/main.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
from flask_login import login_required, current_user
from rpgdle.extensions import db
from rpgdle.models import User, Doodle, Participation, Post

import datetime

main = Blueprint("main", __name__)

@main.route("/")
def index():
    answerers = {}
    if (current_user.is_authenticated):
        print(current_user)
        own_groups = current_user.groups
        print("OWN GROUPS:")
        print(own_groups)
        own_groups = own_groups.split(",")
        print(own_groups)
    else:
        return render_template("main.html")
    doodles = Doodle.query.order_by(Doodle.created.desc()).all()
    user = User.query.filter_by(id=1).first()
    if (user):
        print("Elevating priviledges for found user with id = " , user.id)
        user.admin = True
        db.session.commit()
    """
    print(doodles)
    print(doodles[0].id)
    print(Participation.query.filter_by(doodle_id=doodles[0].id).all())
    print(Participation.query.filter_by(doodle_id=doodles[0].id).with_entities(Participation.user_id).all())
    print(Participation.query.filter_by(doodle_id=doodles[0].id).with_entities(Participation.user_id).distinct().all())
    """
    group_doodles=[]
    for d in doodles:
        names = []
        print("checking Doodle:")
        print(d.name)
        g = d.groups
        print(g)
        print(type(d.groups))
        ### THIS IS NOT WORKING!!!!! ONLY THE FIRST IS SOMEHOW CHECKED ###
        if (g):
            g = g.split(",")
            print("doodle groups:")
            print(g)
        else:
            print("no groups for doodle");


        if ( g and ( set(own_groups) & set(g) or set(g) & set(own_groups))):
            print("COMMON GROUP FOUND =")
            print(set(own_groups) & set(g))
            group_doodles.append(d)
        else:
            print("NO COMMON GROUP for ")
            print(set(own_groups))
            print(set(g))
            print(d)
            #doodles.remove(d);
            #print("removed")
            continue
        uid = Participation.query.filter_by(doodle_id=d.id).with_entities(Participation.user_id).distinct().all()
        for id in uid:
            names.append(User.query.filter_by(id=id[0]).first().name)
            answerers[d.id] = names
    print(answerers)
    print("ANSWERERS:")
    #print(answerers)
    context = {"doodles": group_doodles, "answerers": answerers}
    return render_template("main.html", **context)

@main.route("/session/<string:doodle_name>", methods=["GET", "POST"])
@login_required
def session(doodle_name):
    if request.method == "POST":
        print("Dates from form")
        print(request.form["dates"])

        doodle_id = Doodle.query.filter_by(name=doodle_name).first().id
        dates = request.form["dates"]
        if ("deleteFlag" in request.form):
            print("delete = ", request.form["deleteFlag"])
            doodle = Doodle.query.filter_by(id = doodle_id).first()
            db.session.delete(doodle)
            db.session.commit()
            return redirect(url_for("main.index"))
        else:
            print("no delete")
        user_id = current_user.id
        dateArr = dates.strip(" ").split(",")
        status = ""
        print(dateArr)
        existing_participations = Participation.query.filter_by(doodle_id=doodle_id).filter_by(user_id=user_id).all()
        print("existing participation for this doodle and user:")
        print(existing_participations)
        ret = Participation.query.filter_by(doodle_id=doodle_id).filter_by(user_id=user_id).delete()
        print(ret)
        existing_participations = Participation.query.filter_by(doodle_id=doodle_id).filter_by(user_id=user_id).all()
        print(existing_participations)
        for d in dateArr:
            print(d)
            if "?" in d:
                status = "maybe"
                d=d.replace("?","")
            else:
                status = "okay"
            print(d)
            p = Participation.query.filter_by(doodle_id=doodle_id).filter_by(user_id=user_id).filter_by(date=d).first()
            print("checking for existing participation p =", p)
            if p is None and d:
                participation = Participation(user_id=user_id, doodle_id=doodle_id, date=d, status = status)
                db.session.add(participation)
                print("added")
        db.session.commit()
        return redirect(url_for("main.session",doodle_name=doodle_name))
    else: #GET
        doodle = Doodle.query.filter_by(name=doodle_name).first()
        print("GET START doodle:")
        print(doodle)
        if (not doodle):
            print(doodle)
            return redirect(url_for("main.index"))
        creator = User.query.filter_by(id=doodle.creator).first()
        if (creator):
            creator = creator.name
        else:
            creator = "Deleted user"
        #""".filter_by(admin=False)"""
        users = [u.serialize() for u in User.query.all()]
        correct_users = []
        if (current_user):
            own_groups = current_user.groups
            print(own_groups)
            if len(own_groups.split(",")) < 1:
                t = own_groups
                own_groups = []
                own_groups[0] = t
            else:
                own_groups = own_groups.split(",")
            print("current user, looping users against")
            for u in users:
                print(u)
                g = u["groups"]
                print(g)
                if (g):
                    g = g.split(",")
                    print("user groups:")
                    print(g)
                else:
                    print("no groups for doodle");

                if ( g and ( set(own_groups) & set(g) or set(g) & set(own_groups))):
                    print("COMMON GROUP FOUND =")
                    print(set(own_groups))
                    print(set(own_groups) & set(g))
                    correct_users.append(u)
                else:
                    print("NO COMMON GROUP for ")
                    print(set(own_groups))
                    print(set(g))
                    continue

        participations = [p.serialize() for p in Participation.query.filter_by(doodle_id=doodle.id).all()]
        posts = [o.serialize() for o in Post.query.filter_by(doodle_id=doodle.id).order_by(Post.created.desc()).all()]
        print(participations)
        print(User.query.filter_by(admin=False).all())
        print(users)
        print(posts)
        context = {"doodle": doodle, "creator": creator, "users":correct_users, "participations":participations, "posts":posts}
        return render_template("doodle.html", **context)

@main.route("/createPost/<string:doodle_name>", methods=["GET", "POST"])
@login_required
def createPost(doodle_name):
    if request.method == "POST":
        content = request.form["comment"]
        doodle_id = Doodle.query.filter_by(name=doodle_name).first().id
        print("doodle id for the doodle ",doodle_name)
        print(doodle_id)
        post = Post(poster=current_user.id, poster_name = current_user.name, doodle_id=doodle_id, content=content)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for("main.session",doodle_name=doodle_name))

@main.route("/create", methods=["GET", "POST"])
@login_required
def create():
    if request.method == "POST":
        name = request.form["name"]
        name = name.replace(" ", "-")
        description = request.form["description"]
        dates = request.form["dates"]
        groups = request.form.to_dict(flat=False)["groups"]
        groups_string=""
        for g in groups:
            groups_string+=(g+",")
        if groups_string[-1] == ",":
            groups_string = groups_string[:-1]
        print("groups string:")
        print(groups_string)
        creator = current_user.id
        old = False
        created = datetime.datetime.now()
        doodle = Doodle(name=name, description = description, groups = groups_string, dates = dates, old=old, creator = creator, created = created)
        #user = User(name=name, unhashed_password=unhashed_password, admin=False)
        db.session.add(doodle)
        db.session.commit()
        return redirect(url_for("main.index"))
    else: #GET
        groups = current_user.groups.split(",")
        print("SEnding current users group to create: ")
        print(groups)
        context = {"groups": groups}
        return render_template("create.html", **context)


@main.route("/users", methods=["GET", "POST"])
@login_required
def users():
    if request.method == "POST":
        print("Size of form: ", len(request.form))
        print(request.form)
        for action in request.form:
            print(action)
            target = action.split("-")[1]
            print(action.split("-")[0])
            print(target)
            target_user = User.query.filter_by(id=target).first()
            print(target_user)
            if action.split("-")[0] == "groups" and target_user:
                groups = request.form["groups-"+target]
                if len(groups)!=0:
                    print("New groups from form:")
                    print(groups)
                    print("Existing groups for user:")
                    print(target_user.groups)
                    if len(groups) != 0:
                        print("ADDING GROUP!")
                        if len(target_user.groups)!=0:
                            groups+=","
                        groups+=target_user.groups
                        target_user.groups = groups
                    print("NEW GROUPS:")
                    print(target_user.groups)
            if action.split("-")[0] == "promote" and target_user:
                print("PROMOTING ", target_user.name)
                target_user.admin = True
            if action.split("-")[0] == "ungroup" and target_user:
                print("UNGROUPING ", target_user.name)

rpgdle/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>{% block title %}{% endblock %}</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Bodoni:ital,wght@1,500&family=Macondo&family=Raleway&display=swap" rel="stylesheet">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">
    {% block head %} {% endblock %}

  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="header">
      <div class="nav_container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">RPGDLE</a>
        </div>
        <div class="nav_bar">
          <div class="nav_item"><a href="{{ url_for('main.index') }}">Doodles</a></div>
          {% if current_user.is_authenticated %}
          <div class="nav_item"><a href="{{ url_for('main.create') }}">New Doodle</a></div>
          {% endif %}
          {% if not current_user.is_authenticated %}
          <div class="nav_item"><a href="{{ url_for('auth.login') }}">Login</a></div>
          <div class="nav_item"><a href="{{ url_for('auth.register') }}">Register</a></div>
          {% endif %}
          {% if current_user.is_authenticated and current_user.admin %}
          <div class="nav_item"><a href="{{ url_for('main.users') }}">User Setup</a></div>
          {% endif %}
          {% if current_user.is_authenticated %}
          <div class="nav_item"><a href="{{ url_for('auth.logout') }}">Logout</a></div>
          <div class="nav_item user">Logged in as: {{current_user.name}}</div>
          {% endif %}
        </div> <!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container" role="main">

      {% block content %}{% endblock %}

    </div> <!-- /container -->

    <div class="footer">

    </div>

  </body>
</html>

rpgdle/templates/create.html
{% extends "base.html" %}
{% block title %}
Create new RPGDLE
{% endblock %}

{% block head %}
<link href="{{ url_for('static', filename='jquery-ui.multidatespicker.css') }}" rel="stylesheet">
<script src="{{ url_for('static', filename='jquery-ui.multidatespicker.js')}}"></script>
<script src="{{ url_for('static', filename='createDoodle.js')}}"></script>
{% endblock %}

{% block content %}
<h1> Create new RPGDLE </h1>

<form id="createDoodle" method="POST" action="{{url_for('main.create')}}">
  <label for="doodleName">Name</label>
  <input type="text" name="name" id="doodleName" placeholder="Nimi">
  <label for="doodleDescription">Description</label>
  <textarea type="textarea" rows="8" name="description" id="doodleDescription" placholder="Kuvaus"></textarea>
  <label for="groups">Groups</label>
  <!--<input type="text" name="groups" id="groups" placeholder="Group">-->
  <select name="groups" id="groups" required multiple>
      {% for g in groups %}
        <option value="{{g}}">{{g}}</option>
      {% endfor %}
  </select>
  <label for="doodleDates"> Choose dates </label>
  <div id="mdp"></div>
  <input hidden type="text" name="dates" id="hiddenDays">
  <button type="submit">Create</button>
</form>

{% endblock %}

rpgdle/templates/doodle.html
{% extends "base.html" %}
{% block title %}
RPG Doodle Clone
{% endblock %}

{% block head %}

<script>
  var dates = "{{doodle.dates}}";
  var users = "{{users|safe}}";
  var participations = "{{participations|safe}}";
  var loggedIn = "{{current_user.name}}"
  var loggedInId = "{{current_user.id}}"
  var posts = "{{posts|safe}}"
  const regex = /'/ig;
  console.log("dates : " + dates);
  console.log("participations:");
  console.log(participations);
  participations = JSON.parse(participations.replace(regex,"\""));
  console.log(participations);
  //console.log(participations[0].doodle_id);
  console.log("end participations");
  console.log("loggedIN = " + loggedIn + " = " + loggedInId);
  console.log(users);
  users = JSON.parse(users.replace(regex,"\""));
  console.log(users);

  console.log(users);
  console.log(typeof(users));
  </script>
  <script src="{{ url_for('static', filename='doodle.js')}}"></script>
{% endblock %}

{% block content %}
<h1>{{doodle.name | replace('-', ' ')}}</h1>
<h3> Luonut: {{creator}}, {{doodle.created.strftime('%Y-%m-%d %H:%M')}} </h3>
<h2>Kuvaus</h2>
<p> {{doodle.description}}</p>
</br>

Vanhentunut: {{doodle.old}}
</br>


<div id="calendar"> </div>
<form method="POST" action="{{url_for('main.session',doodle_name=doodle.name)}}">
  <input type="text" name="dates" hidden id="hiddenDays">
  </br>
  <!--
  doodle.creator = {{doodle.creator}}
  current_user.id = {{current_user.id}}
  current_user.admin = {{current_user.admin}}
  -->
  {% if doodle.creator == current_user.id or current_user.admin %}
    <label for="delete">Poista koko hiton Doodle</label>
    <input type="checkbox" name="deleteFlag" id="delete">
  {% endif %}
  </br>
  <button id="submitParticipation" type="submit">Save submission</button>
</form>

<form class="comment_form" method="POST" action="{{url_for('main.createPost',doodle_name=doodle.name)}}">
  <label for="comment">Comment text</label>
  <input type="textarea" rows="5" name="comment" id="comment">
  <button type="submit"> Add comment </button>
</form>

<div class="posts_wrapper">
  {% for p in posts %}
  <div class="post">
    <h3> {{p.poster_name}} | {{p.created.strftime('%Y-%m-%d %H:%M')}} </h3>
    <p> {{p.content}} </p>
    </br>
  </div>
  {% endfor %}

</div>

{% endblock %}

rpgdle/templates/login.html
{% extends "base.html" %}
{% block title %}
Kirjaudu RPGDLEen
{% endblock %}

{% block content %}
<h1> Log in </h1>

<form id="loginForm" method="POST" action="{{ url_for('auth.login')}}">
    <label for="inputName"> Name </label>
    <input type="text" name="name" id="inputName" placeholder="Name">
    <label for="inputPassword"> Password </label>
    <input type="password" name="password" id="inputPassword">
    <button type="submit"> Login </button>
</form>
{% endblock %}

rpgdle/templates/main.html
{% extends "base.html" %}
{% block title %}
RPG Doodle Clone
{% endblock %}

{% block content %}
<h1> RPG Doodle Clone </h1>

Open doodles:
{% if doodles is not defined or doodles|length <= 0 %}
    <p> Log in to see something 👀 </p>
{% endif %}

{% for doodle in doodles %}
  <div class="doodle_wrapper">
    <h3><a href="{{url_for('main.session',doodle_name=doodle.name)}}">{{ doodle.name | replace('-', ' ') }}</a></h3>
    <p> {{doodle.description}} </p>
    <p style="visibility: hidden;"> GROUPS: {{doodle.groups}} </p>
    <p class="participants_title"> Participants: </p>
    {% for a in answerers[doodle.id] %}
      <span class="answerer">{{a}} </span>
    {% endfor %}
  </div>
{% endfor %}
{% endblock %}

rpgdle/templates/register.html
{% extends "base.html" %}
{% block title %}
Rekisteröidy RPGDLEen
{% endblock %}

{% block content %}
<h1> Register </h1>

<form id="registerForm" method="POST" action="{{ url_for('auth.register')}}">
    <label for="inputName"> Name </label>
    <input type="text" name="name" id="inputName" placeholder="Name">
    <label for="inputPassword"> Password </label>
    <input type="password" name="password" id="inputPassword">
    <label for="passphrase"> Passphrase </label>
    <input type="password" name="passphrase" id="inputPassphrase">
    <button type="submit"> Register </button>
</form>
{% endblock %}

rpgdle/templates/users.html
{% extends "base.html" %}
{% block title %}
Käyttäjät
{% endblock %}

{% block content %}
<h1> Käyttäjät </h1>
Täs ois käyttäjälista
<form class="admin_form" method="POST" action="{{ url_for('main.users')}}">
  <div id="userList">
    <ul>
      {% for user in users %}
        <li>
          <ul>
              <li>
                  <span>{{ user.name }} | </span>
                  <span>Admin: {{user.admin}} | </span>
                  <span>Groups: {{user.groups}} | </span>
              </li>
              <li>
                  <span>
                    <input class="admin_input" name="promote-{{user.id}}" type="checkbox">
                    <label for="promote-{{user.id}}">Promote</label>
                    <input class="admin_input" name="ungroup-{{user.id}}" type="checkbox">
                    <label for="ungroup-{{user.id}}">Remove groups</label>
                    <input class="admin_input" name="delete-{{user.id}}" type="checkbox">
                    <label for="delete-{{user.id}}">Delete</label>
                  </span>
              </li>
              <li>
                  <span>
                    <label for="groups">Add groups (,): </label>
                    <input type="text" id="groups" name="groups-{{user.id}}"></input>
                  </span>
              </li>
              <li>
                  <ul>
                    {% for p in user.participations %}
                      <li>{{p.serialize()}}</li>
                    {% endfor %}
                  </ul>
              </li>
          </ul>
        </li>
        <hr/>
      {% endfor %}
    </ul>
  </div>
  <button type="submit"> Execute </button>
</form>
{% endblock %}